### ISSUE TITLE
Reading the chipid gives nonzero "random" number.

### ISSUE THREAD

**Issue by rewolff** [texane/stlink#240]
When starting st-util on my F4 discovery board, I got: 

 WARN src/stlink-common.c: unknown chip id! 0xe0042000
 Chip ID is 00000000, Core ID is  00000000.

which I know spells trouble. But when I see some non-zero numbers for the "chip id" I think I have a connection to the target. Turns out that is not the case: When I switched back to my target I got the same 0xe0042000 chip id, even when the target was not powered. 

My STM32F407 on my discovery board might be fried, I don't know yet. I'll just use the F4DISCOVERY as my STLINK for now. 

It'd be nice if the "detection" of "no chip connected" was a bit better. Apparently "chip id = 0xe0042000, ... core id = 0" means "no chip"....

**Comment by xor-gate** [comment]
I'm closing this old issue. As it should now be tested against master. Please reopen a new issue when similar problem exists.

**Comment by Nightwalker-87** [comment]
Can someone verify that this has been fixed?

**Comment by rewolff** [comment]
The weirdness still exist.It seems I was still "new" to stm32 when I reported this. It is now firmly implanted in my brain that the 0xe004200 means "no chip". 
```
assurancetourix:~/stm32/stlink.git> ./st-util -m
2020-02-26T18:36:19 INFO src/common.c: Loading device parameters....
2020-02-26T18:36:19 WARN src/common.c: unknown chip id! 0xe0042000
assurancetourix:~/stm32/stlink.git> 
```

**Comment by Nightwalker-87** [comment]
@rewolff: Feedback like yours gives me the impression and feeling that it is _really_ worth it to review all closed issues of this project for leftovers no matter when they occurred. I am really sorry that you had to deal with this problem for such a long time - very unsatisfiable indeed. Trying to push the priority up for this.

**Comment by Nightwalker-87** [comment]
@rewolff: Your proposal seems very reasonable to me. If you fancy, you may submit a PR for this which is linked to this issue.

**Comment by Nightwalker-87** [comment]
BTW: I assume there may be more of these "hidden" error codes that could see some "decription" as well.

**Comment by rewolff** [comment]
Working on it.... 

FYI, I had trouble getting an STM recognized. Probably an older version of stlink. Getting latest now. 

```
assurancetourix:~> st-util -m
2020-03-21T15:05:04 INFO src/stlink-common.c: Loading device parameters....
2020-03-21T15:05:04 WARN src/stlink-common.c: unknown chip id! 0xe0042000
assurancetourix:~> st-util -m
2020-03-21T15:05:39 INFO src/stlink-common.c: Loading device parameters....
2020-03-21T15:05:39 WARN src/stlink-common.c: unknown chip id! 0

```

**Comment by Nightwalker-87** [comment]
Yes, please use v1.6.0 or even `develop` which itself is despite of the name also fairly stable.

**Comment by Nightwalker-87** [comment]
Note: PRs will go into `develop` anyway. Please consider this when opening such in the future.

**Comment by rewolff** [comment]
Sorry, didn't see your remark about using develop until after I finished the PR. Can you cope or do I need to redo it?

**Comment by Nightwalker-87** [comment]
No that's ok, I can fix this as well. I know this is a bit annoying to contributors. :-/ I've already consulted texane to switch the base branch to `develop` what would take this additional consideration away from users. If I could, I would have done that already.

**Comment by Nightwalker-87** [comment]
> The weirdness still exist.It seems I was still "new" to stm32 when I reported this. It is now firmly implanted in my brain that the 0xe004200 means "no chip".
> 
> ```
> assurancetourix:~/stm32/stlink.git> ./st-util -m
> 2020-02-26T18:36:19 INFO src/common.c: Loading device parameters....
> 2020-02-26T18:36:19 WARN src/common.c: unknown chip id! 0xe0042000
> assurancetourix:~/stm32/stlink.git> 
> ```
> 
> Just FYI:
> The desired situation would be that the "read chip ID" function can return -1 as "error", and that instead of printing "unknown chip id 0xfffffff" the message would read something like: Error: No chip found.

@rewolff: We should have a new ticket for this as it did not make it into PR 886.

**Comment by rewolff** [comment]
My testing shows that it does sensible things now. That's why I didn't do anything for this. 

OK... Mine now says: 
`2020-03-22T12:05:32 WARN common.c: Invalid flash type, please check device declaration
`
and doesn't consider that fatal. I can dive in and make this message "fatal", but I don't know if it maybe makes sense to have the debugger connected without knowing "flash type"? Maybe debugging works, but flashing new firmware not?
